# Generated by Django 4.1 on 2024-05-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("TITLE", models.CharField(max_length=225)),
                ("DESCRIPTION", models.TextField()),
                ("RELEASE_DATE", models.DateField()),
                (
                    "GENRE",
                    models.CharField(
                        choices=[
                            ("action", "Action"),
                            ("comedy", "Comedy"),
                            ("drama", "Drama"),
                        ],
                        max_length=100,
                    ),
                ),
                ("length", models.PositiveIntegerField()),
                ("image_card", models.ImageField(upload_to="movie_images/")),
                ("image_cover", models.ImageField(upload_to="movie_videos/")),
                ("movie_views", models.IntegerField(default=0)),
            ],
        ),
    ]
