# Generated by Django 4.1 on 2024-05-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0002_rename_genre_movies_category_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movies",
            old_name="CATEGORY",
            new_name="GENRE",
        ),
        migrations.RenameField(
            model_name="movies",
            old_name="POSTER",
            new_name="image_card",
        ),
        migrations.RemoveField(
            model_name="movies",
            name="YOUTUBE_TRAILER",
        ),
        migrations.AddField(
            model_name="movies",
            name="image_cover",
            field=models.ImageField(
                default="default_image.jpg", upload_to="movie_videos/"
            ),
        ),
        migrations.AddField(
            model_name="movies",
            name="length",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="movies",
            name="movie_views",
            field=models.IntegerField(default=0),
        ),
    ]
