# Generated by Django 4.1 on 2024-05-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0004_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name="movies",
            old_name="GENRE",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="movies",
            old_name="DESCRIPTION",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="movies",
            old_name="image_card",
            new_name="poster",
        ),
        migrations.RenameField(
            model_name="movies",
            old_name="RELEASE_DATE",
            new_name="release_date",
        ),
        migrations.RenameField(
            model_name="movies",
            old_name="TITLE",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="movies",
            name="image_cover",
        ),
        migrations.AddField(
            model_name="movies",
            name="trailer_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movies",
            name="actors",
            field=models.ManyToManyField(related_name="movies", to="movie.actor"),
        ),
    ]
