# Generated by Django 4.1 on 2024-05-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0005_actor_rename_genre_movies_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movies",
            name="actors",
        ),
        migrations.DeleteModel(
            name="Actor",
        ),
        migrations.AddField(
            model_name="movies",
            name="actors",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
