# Generated by Django 4.1 on 2024-05-17 11:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0006_remove_movies_actors_delete_actor_movies_actors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movies",
            name="length",
        ),
        migrations.RemoveField(
            model_name="movies",
            name="movie_views",
        ),
    ]
