# Generated by Django 4.1 on 2024-05-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0012_category_alter_movies_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movies",
            name="category",
            field=models.CharField(
                choices=[
                    ("action", "Action"),
                    ("comedy", "Comedy"),
                    ("drama", "Drama"),
                ],
                max_length=100,
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
