# Generated by Django 4.1 on 2024-05-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("film", "0005_movie_movielist"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
