# Generated by Django 4.1 on 2024-05-20 11:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("film", "0006_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
    ]
